### PR TITLE
Fixes issue #10

### LINKED ISSUE #10: Add responsive tables
At the moment a large table will grow and break the `.container` on small screens.
It would be much better if tables automatically scroll left and right when the viewport is too small.

### PR DESCRIPTION
**Pull request by ShivamRawat0l**
Added css for responsive table. fixes #10

### CODE REVIEW

**Comment by Gioni06** [comment]
Thanks for the PR.. i'll take a look at it asap!

**Comment by ShivamRawat0l** [comment]
Ok I will try to do it

**Comment by Gioni06** [comment]
@ShivamRawat0l Any updates on this PR ?

**Comment by ShivamRawat0l** [comment]
Sorry. I got exams therefore i am busy this month.

**Comment by Gioni06** [comment]
@ShivamRawat0l Still interested in this MR?

**Comment by ShivamRawat0l** [comment]
> 
> 
> @ShivamRawat0l Still interested in this MR?

I ll try my best if get an opportunity. Might take time : )

**Comment by Gioni06** [comment]
since there is no movement on this issue I'll close this PR. When you're interested in this issue, just reopen it :)

**Pull request closed without merging**
