### PR TITLE
Add timeline component

### PR DESCRIPTION
**Pull request by othyn**
Just made a history section for my personal website and thought it'd be cool to share!

A timeline component that can be easily created by wrapping existing `.terminal-card`'s within a containing `.terminal-timeline`.

:)

### CODE REVIEW

**Comment by Gioni06** [comment]
Wow, thanks! That looks awesome

**Comment by Gioni06** [comment]
@othyn I fixed some linting issues, but everything was good. I sent you an invite to contribute to this repository if you like. A new version with your changes was just published on npm.

**Comment by othyn** [comment]
Awesome, thank you! I may have to have a fiddle at some point in future ;)

**Comment by Gioni06** [comment]
And you shall have one :)

**Pull request merged**
