### PR TITLE
Fixes the button borders on Safari

### PR DESCRIPTION
**Pull request by matiaskorhonen**
This should fix issue #12.

I tried it on Safari but I don't have a Windows install of Vivaldi on hand to try it there.

### CODE REVIEW

**Comment by Gioni06** [comment]
Hi, thanks for the PR. A lot going on lately and somehow I missed your PR :) I'll review it and check it.

**Comment by Gioni06** [comment]
Released with v0.6.6
Thanks @matiaskorhonen

**Comment by Gioni06** [comment]
@matiaskorhonen I'm thinking about a "Projects using Terminal.css" section on the website. May I add a link to your website?

**Comment by matiaskorhonen** [comment]
Sure, both my homepage (https://matiaskorhonen.fi/) and blog (https://www.randomerrata.com/) are using terminal.css. The blog is probably the better showcase as it has more content…

**Pull request merged**
